package cz.jkapoun.todo.presenters;

import com.vaadin.spring.annotation.UIScope;
import cz.jkapoun.todo.model.Task;
import cz.jkapoun.todo.model.TaskRepository;
import cz.jkapoun.todo.views.TodoView;
import java.util.Collection;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

/**
 * Presenter class of the main application UI.
 * Provides the view with a data model and handles the UI events generated by
 * user actions.
 * 
 * @author Jiří Kapoun <jiri.kapoun@profinit.eu>
 * @see    TodoView
 */
@Component
@UIScope
public class TodoPresenter implements TodoView.TodoViewListener {

  protected TaskRepository taskService;
  protected TodoView    todoView;

  @Autowired
  public TodoPresenter(TaskRepository taskService, TodoView todoView) {
    this.taskService = taskService;
    this.todoView    = todoView;

    Collection<Task> tasks = taskService.getTasks();

    todoView.addListener(this);
    todoView.init();
    todoView.displayTasks(tasks);
  }

  @Override
  public void handleAddTask(String text) {
    taskService.addTask(text);
    todoView.clearField();
    todoView.refreshData();
    todoView.showNotification("Task added");
  }

  @Override
  public void handleDeleteTask(Task task) {
    int id = task.getId();
    taskService.deleteTask(id);
    todoView.refreshData();
    todoView.showNotification("Task deleted");
  }
}
